use_frameworks!

platform :ios, '10.0'

target 'DebugKit_Example' do
  pod 'DebugKit', :path => '../', :subspecs => [
    'Core',
    'Log',
    'FileLogViewer',
    'JsonViewer',
    'UserDefaults',
    'MsgSimulation',
  ]

  target 'DebugKit_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 9.2.1'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end

